import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/container";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, height=device-height"
        /> */}
      </head>
      <body>
        <Header />
        <main className="pt-[var(--nav-height)]">{children}</main>
        <footer>
          <Container>footer</Container>
        </footer>
      </body>
    </html>
  );
}
